site_name: Anthropic on AWS
theme:
  name: material
  font:
    text: 'Segoe UI'
    code: 'Roboto Mono'
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: indigo
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: indigo
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - bash
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - content.code.copy
plugins:
  - search
  - glightbox
  - include-markdown
  - minify:
      minify_html: true
  - social:
      cards: true
      cards_layout_options:
        font_family: Roboto
nav:
  - Home: index.md
  - Projects:
      - Classification with Intercom: projects/classification-with-intercom.md
      - Claude Multimodal LLM Playground:
          - Overview: projects/claude-multimodal-llm-playground.md
          - Anthropic: projects/claude-multimodal-llm-playground/anthropics/README.md
          - Bedrock: projects/claude-multimodal-llm-playground/bedrock/README.md
      - Claude Tools Chatbot: projects/claude-tools-chatbot.md
      - Complex Schema Tool Use:
          - Overview: projects/complex-schema-tool-use.md
          - NextJS Typescript Example: projects/complex-schema-tool-use/nextjs-typescript-example.md
          - Streamlit Python Example: projects/complex-schema-tool-use/streamlit-python-example.md
          - Streamlit Stepfunction Example: projects/complex-schema-tool-use/streamlit-stepfunction-example.md
      - Metaprompt Generator: projects/metaprompt-generator.md
