name: 'Release Docs'
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-glightbox
          pip install mkdocs-minify-plugin
          pip install mkdocs-material-extensions
          pip install pillow cairosvg
          pip install mkdocs-include-markdown-plugin
      - name: Copy subproject images
        run: python copy_subproject_images.py
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
